### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by riker65** [bkmistry1/blackvue_vod_download#1]
Hi 
this looks very interessting.

I am a python dummy, so maybe I did something wrong.

Looking hat http://192.168.6.215/blackvue_vod.cgi 
I do see 
`v:3.00
n:/Record/20241226_164917_PF.mp4,s:1000000
n:/Record/20241226_165328_IF.mp4,s:1000000
n:/Record/20241226_165428_NF.mp4,s:1000000
n:/Record/20241226_165529_NF.mp4,s:1000000
n:/Record/20241226_165629_NF.mp4,s:1000000
n:/Record/20241226_165729_NF.mp4,s:1000000
n:/Record/20241226_165830_NF.mp4,s:1000000
n:/Record/20241226_165930_NF.mp4,s:1000000
n:/Record/20241226_170030_NF.mp4,s:1000000
n:/Record/20241226_170131_NF.mp4,s:1000000
n:/Record/20241226_170231_NF.mp4,s:1000000
n:/Record/20241226_170246_PF.mp4,s:1000000`

but when I am running this I get an error:

`Traceback (most recent call last):
  File "C:\Users\riker\blackvue\blackvue_vod_download.py", line 109, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\riker\blackvue\blackvue_vod_download.py", line 83, in main
    fileList = await getFileList()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riker\blackvue\blackvue_vod_download.py", line 28, in getFileList
    url = ip + "/blackvue_vod.cgi"
          ~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by bkmistry1** [comment]
hello, 

so I should probably create an instructions for this project at some point. This project requires a ".env" file within the folder for 3 environment variables: 

1. blackvueIP
2. downloadFolder
3. tmpFolder

I think this might be why you are having an issue.

![bCapture](https://github.com/user-attachments/assets/e1779471-4a35-4fe1-89cc-5583575e16a0)

**Comment by riker65** [comment]
ok thanks, 
does the  env file has a special naming convention? or just blackvue.env?

**Comment by bkmistry1** [comment]
it should just be:
.env
![image](https://github.com/user-attachments/assets/0669c2c1-4911-4ba9-a576-1603cc5d9ad2)
